package me.EzCoins.MiniBlocks.Core;

public class TranslateBlocks {
    public static String translateBlocksName(String name) {
        switch (name) {
            case "STONE":
                return "石頭";
            case "GRANITE":
                return "花崗岩";
            case "POLISHED_GRANITE":
                return "拋光花崗岩";
            case "DIORITE":
                return "閃長岩";
            case "POLISHED_DIORITE":
                return "拋光閃長岩";
            case "ANDESITE":
                return "安山岩";
            case "POLISHED_ANDESITE":
                return "拋光安山岩";
            case "DEEPSLATE":
                return "深板岩";
            case "COBBLED_DEEPSLATE":
                return "深板岩碎石";
            case "POLISHED_DEEPSLATE":
                return "拋光深板岩";
            case "CALCITE":
                return "方解石";
            case "TUFF":
                return "凝灰岩";
            case "DRIPSTONE_BLOCK":
                return "鐘乳石方塊";
            case "GRASS_BLOCK":
                return "草地";
            case "DIRT":
                return "泥土";
            case "COARSE_DIRT":
                return "粗泥";
            case "PODZOL":
                return "灰壤";
            case "ROOTED_DIRT":
                return "扎根土";
            case "CRIMSON_NYLIUM":
                return "緋紅菌絲石";
            case "WARPED_NYLIUM":
                return "扭曲菌絲石";
            case "COBBLESTONE":
                return "鵝卵石";
            case "OAK_PLANKS":
                return "橡木材";
            case "SPRUCE_PLANKS":
                return "杉木材";
            case "BIRCH_PLANKS":
                return "樺木材";
            case "JUNGLE_PLANKS":
                return "叢林木材";
            case "ACACIA_PLANKS":
                return "相思木材";
            case "DARK_OAK_PLANKS":
                return "黑橡木材";
            case "CRIMSON_PLANKS":
                return "緋紅蕈木材";
            case "WARPED_PLANKS":
                return "扭曲蕈木材";
            case "BEDROCK":
                return "基岩";
            case "SAND":
                return "沙";
            case "RED_SAND":
                return "紅沙";
            case "GRAVEL":
                return "礫石";
            case "COAL_ORE":
                return "煤礦";
            case "DEEPSLATE_COAL_ORE":
                return "深板岩煤礦";
            case "IRON_ORE":
                return "鐵礦";
            case "DEEPSLATE_IRON_ORE":
                return "深板岩鐵礦";
            case "COPPER_ORE":
                return "銅礦";
            case "DEEPSLATE_COPPER_ORE":
                return "深板岩銅礦";
            case "GOLD_ORE":
                return "金礦";
            case "DEEPSLATE_GOLD_ORE":
                return "深板岩金礦";
            case "REDSTONE_ORE":
                return "紅石礦";
            case "DEEPSLATE_REDSTONE_ORE":
                return "深板岩紅石礦";
            case "EMERALD_ORE":
                return "綠寶石礦";
            case "DEEPSLATE_EMERALD_ORE":
                return "深板岩綠寶石礦";
            case "LAPIS_ORE":
                return "青金石礦";
            case "DEEPSLATE_LAPIS_ORE":
                return "深板岩青金石礦";
            case "DIAMOND_ORE":
                return "鑽石礦";
            case "DEEPSLATE_DIAMOND_ORE":
                return "深板岩鑽石礦";
            case "NETHER_GOLD_ORE":
                return "地獄金礦";
            case "NETHER_QUARTZ_ORE":
                return "地獄石英礦";
            case "ANCIENT_DEBRIS":
                return "遠古遺骸";
            case "COAL_BLOCK":
                return "煤炭方塊";
            case "RAW_IRON_BLOCK":
                return "鐵原礦方塊";
            case "RAW_COPPER_BLOCK":
                return "銅原礦方塊";
            case "RAW_GOLD_BLOCK":
                return "金原礦方塊";
            case "AMETHYST_BLOCK":
                return "紫水晶方塊";
            case "BUDDING_AMETHYST":
                return "紫水晶芽床";
            case "IRON_BLOCK":
                return "鐵方塊";
            case "COPPER_BLOCK":
                return "銅方塊";
            case "GOLD_BLOCK":
                return "黃金方塊";
            case "DIAMOND_BLOCK":
                return "鑽石方塊";
            case "NETHERITE_BLOCK":
                return "獄髓方塊";
            case "EXPOSED_COPPER":
                return "斑駁的銅方塊";
            case "WEATHERED_COPPER":
                return "風化的銅方塊";
            case "OXIDIZED_COPPER":
                return "氧化的銅方塊";
            case "CUT_COPPER":
                return "切製銅方塊";
            case "EXPOSED_CUT_COPPER":
                return "斑駁的切製銅方塊";
            case "WEATHERED_CUT_COPPER":
                return "風化的切製銅方塊";
            case "OXIDIZED_CUT_COPPER":
                return "氧化的切製銅方塊";
            case "OAK_LOG":
                return "橡木原木";
            case "SPRUCE_LOG":
                return "杉木原木";
            case "BIRCH_LOG":
                return "樺木原木";
            case "JUNGLE_LOG":
                return "叢林木原木";
            case "ACACIA_LOG":
                return "相思木原木";
            case "DARK_OAK_LOG":
                return "黑橡木原木";
            case "CRIMSON_STEM":
                return "緋紅蕈柄";
            case "WARPED_STEM":
                return "扭曲蕈柄";
            case "BEACON":
                return "烽火台";
            case "STRUCTURE_VOID":
                return "結構空位";
            case "BARRIER":
                return "屏障";
            case "GLOWSTONE":
                return "螢光石";
            case "SOUL_SAND":
                return "靈魂砂";
            case "SOUL_SOIL":
                return "靈魂土";
            case "HONEY_BLOCK":
                return "蜂蜜塊";
            case "BONE_BLOCK":
                return "骨塊";
            case "SLIME_BLOCK":
                return "史萊姆方塊";
            case "SOUL_CAMPFIRE":
                return "靈魂營火";
            case "CAMPFIRE":
                return "營火";
            case "BEE_NEST":
                return "蜂窩";
            case "LODESTONE":
                return "磁石";
            case "CRYING_OBSIDIAN":
                return "哭泣的黑曜石";
            case "SOUL_LANTERN":
                return "靈魂燈籠";
            case "LANTERN":
                return "燈籠";
            case "SHROOMLIGHT":
                return "蕈光體";
            case "REDSTONE_LAMP":
                return "紅石燈";
            case "JACK_O_LANTERN":
                return "南瓜燈";
            case "DEAD_BUSH":
                return "枯灌木";
            case "TOTEM_OF_UNDYING":
                return "不死圖騰";
            case "SCULK_SENSOR":
                return "伏聆振測器";
            case "SCAFFOLDING":
                return "鷹架";
            case "LAVA_BUCKET":
                return "熔岩桶";
            case "WATER_BUCKET":
                return "水桶";
            case "MILK_BUCKET":
                return "鮮奶桶";
            case "POWDER_SNOW_BUCKET":
                return "粉雪桶";
            case "BUCKET":
                return "鐵桶";
            case "ROSE_BUSH":
                return "玫瑰叢";
            case "CHEST":
                return "儲物箱";
            case "COCOA_BEANS":
                return "可可豆";
            case "SPYGLASS":
                return "望遠鏡";
            case "BRICKS":
                return "紅磚頭";
            case "JUKEBOX":
                return "唱片機";
            case "COMMAND_BLOCK":
                return "指令方塊";
            case "CHAIN_COMMAND_BLOCK":
                return "連鎖式指令方塊";
            case "REPEATING_COMMAND_BLOCK":
                return "重複型指令方塊";
            case "CACTUS":
                return "仙人掌";
            case "OBSERVER":
                return "偵測器";
            case "SLIME_BALL":
                return "史萊姆球";
            case "MAGMA_CREAM":
                return "岩漿球";
            case "PISTON":
                return "活塞";
            case "STICKY_PISTON":
                return "黏性活塞";
            case "TARGET":
                return "標靶";
            case "CRAFTING_TABLE":
                return "工作台";
            case "STONECUTTER":
                return "切石機";
            case "GRINDSTONE":
                return "砂輪";
            case "FLETCHING_TABLE":
                return "製箭台";
            case "SMITHING_TABLE":
                return "鍛造台";
            case "CARTOGRAPHY_TABLE":
                return "製圖台";
            case "ENCHANTING_TABLE":
                return "附魔台";
            case "ENCHANTED_BOOK":
                return "附魔書";
            case "LOOM":
                return "紡織機";
            case "LECTERN":
                return "講台";
            case "CAULDRON":
                return "鍋釜";
            case "FURNACE":
                return "熔爐";
            case "BLAST_FURNACE":
                return "高爐";
            case "SMOKER":
                return "煙燻爐";
            case "ANVIL":
                return "鐵砧";
            case "CHIPPED_ANVIL":
                return "微損的鐵砧";
            case "DAMAGED_ANVIL":
                return "耗損的鐵砧";
            case "END_CRYSTAL":
                return "終界水晶";
            case "SPONGE":
                return "海綿";
            case "WET_SPONGE":
                return "濕海綿";
            case "CAKE":
                return "蛋糕";
            case "COOKIE":
                return "餅乾";
            case "PUMPKIN_PIE":
                return "南瓜派";
            case "SUGAR_CANE":
                return "甘蔗";
            case "PUMPKIN":
                return "南瓜";
            case "CARVED_PUMPKIN":
                return "雕刻過的南瓜";
            case "MELON":
                return "西瓜";
            case "TNT":
                return "TNT";
            default:
                return "錯誤，無翻譯 " + name;
        }
    }
}
